# ============================================================
#  PedidosApi — Canary Release (Docker Hub)
# ============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidosapi
  namespace: stable
  labels:
    app: pedidosapi
    track: stable
spec:
  replicas: 9
  selector:
    matchLabels:
      app: pedidosapi
      track: stable
  template:
    metadata:
      labels:
        app: pedidosapi
        track: stable
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: pedidosapi
        image: maqbrdevops/pedidosapi:1.0.9
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: pedidosapi-config
        - secretRef:
            name: pedidosapi-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidosapi-canary
  namespace: stable
  labels:
    app: pedidosapi
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidosapi
      track: canary
  template:
    metadata:
      labels:
        app: pedidosapi
        track: canary
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: pedidosapi
        image: maqbrdevops/pedidosapi:1.1.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: pedidosapi-config
        - secretRef:
            name: pedidosapi-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pedidosapi-svc
  namespace: stable
spec:
  type: LoadBalancer
  selector:
    app: pedidosapi
  ports:
  - port: 80
    targetPort: 8080
