apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidosapi-config
  namespace: NAMESPACE_TAG    # ← placeholder alpha | beta | rc | stable
  labels:
    app: pedidosapi
data:
  ASPNETCORE_ENVIRONMENT: "ENV_TAG"    # ← placeholder Alpha | Beta | RC | Stable
  ASPNETCORE_URLS: "http://+:8080"
  DOTNET_RUNNING_IN_CONTAINER: "true"
